# コロケーション {#collocation}

## 文書内での共起

共起関係を数える機能はgibasaには実装されていません。文書内での共起を簡単に数えるには、たとえば次のようにします。

```{r}
dat_fcm <- dat_count |>
  tidytext::cast_dfm(doc_id, token, n) |>
  quanteda::fcm()

dat_fcm
```

## 任意のウィンドウ内での共起

### 共起の集計

`RMeCab::collocate`のような任意のウィンドウの中での共起を集計するには、次のようにする必要があります。ここではwindowは前後5個のトークンを見るようにします。

```{r}
dat_corpus <- dat |>
  gibasa::pack()

dat_fcm <- dat_corpus |>
  quanteda::corpus() |>
  quanteda::tokens(what = "fastestword") |>
  quanteda::fcm(context = "window", window = 5)
```

こうすると、nodeについて共起しているtermとその頻度を確認できます。以下では、「わたくし」というnodeと共起しているtermで頻度が上位20までであるものを表示しています。

```{r}
dat_fcm <- dat_fcm |>
  tidytext::tidy() |>
  dplyr::rename(node = document, term = term) |>
  dplyr::filter(node == "わたくし") |> 
  dplyr::slice_max(count, n = 20)

dat_fcm
```

### T値やMI値の算出

T値やMI値は、たとえば次のようにして計算できます。

```{r}
ntok <- dat_corpus |>
  quanteda::corpus() |>
  quanteda::tokens(what = "fastestword") |>
  quanteda::ntoken() |>
  sum()

total <- dat_corpus |>
  quanteda::corpus() |>
  quanteda::tokens(what = "fastestword") |>
  quanteda::tokens_select(c("わたくし", dat_fcm$term)) |>
  quanteda::dfm() |>
  quanteda::colSums()

dat_fcm |>
  dplyr::select(-node) |>
  dplyr::mutate(
    expect = count / (total[term] / ntok * total["わたくし"] * 5 * 2),
    t = (count - expect) / sqrt(count),
    mi = log2(count / expect)
  )
```
